[build-system]
requires = ["setuptools>=80.9.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "conotes"
version = "0.0.1.dev251117"
description = "Note taking tool from console."
authors = [
    { name = "stpatrirach" }
]
requires-python = ">=3.7"
dependencies = [
    "mdutils 1.8.1",

    ]

[tool.setuptools]
packages = ["conotes"]
package-dir = {"" = "src"}

