[build-system]
requires = ["setuptools>=80.9.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "conotes"
version = "0.0.1.dev251117"
description = "Note taking tool from console."
authors = [
    { name = "stpatrirach" }
]
requires-python = ">=3.7"
dependencies = [
    "lib>=0.4.6",
    "lib>=3.1.5",
    "lib>=80.9.0"
]

[tool.setuptools]
packages = ["conotes"]
package-dir = {"" = "src"}

